version: '2'
services:
  web:
    restart: always
    container_name: "fplay_api_docker"
    build: ./web
    expose:
      - 8000
    volumes:
    - /usr/src/app/templates/static
    env_file: dev.env
    command: /usr/local/bin/gunicorn main:app --bind :8000 --worker-class aiohttp.worker.GunicornWebWorker
  redis:
    image: redis:3.2-alpine
    container_name: "redis"
    ports:
      - 6378:6379
    volumes:
      - redis_data:/data
  rcli:
    image: redis:3.2-alpine
    links:
      - redis
    command: redis-cli -h redis
volumes:
  redis_data: