redis:
  host: 127.0.0.1
  port: 6379
  db: 1
  minsize: 1
  maxsize: 5

host: 127.0.0.1
port: 6969
vod:
  list_vod_user: "histories:list:%s"
  vod_history: "histories:%s:%s"
  max_vod_per_user: 100
  vod_timeout_secs: 2592000